version: 0.0
os: windows
files:
 - source: .
   destination: C:\Users\Administrator\Documents\code-deploy-geoportal
hooks:
  AfterInstall:
   - location: scripts/install_app_dependencies
     timeout: 300
  ApplicationStart:
   - location: scripts/start_server
     timeout: 300
