version: 0.0
os: windows
files:
 - source: .
   destination: C:\Users\Administrator\Documents\code-deploy
hooks:
  AfterInstall:
   - location: scripts/install_app_dependencies.bat
     timeout: 3600
  ApplicationStart:
   - location: scripts/start_server.bat
     timeout: 3600
